'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
let assertions=0;
const ok=(value,message)=>{assertions++;assert.ok(value,message)};
const equal=(actual,expected,message)=>{assertions++;assert.strictEqual(actual,expected,message)};
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/app-shell-branding.css'),'utf8');
const preview=fs.readFileSync(path.join(root,'app-shell.preview.local.html'),'utf8');

equal((html.match(/assets\/branding\/mentoria-black-icon-512\.png/g)||[]).length,2,'login and app shell use the approved official symbol');
ok(!/<svg class="crest"/.test(html),'legacy inline MB crests are removed');
ok(!/<text[^>]*>MB<\/text>/.test(html),'legacy simplified MB monogram is absent');
ok(html.includes('class="brand-full auth-brand"'),'login owns a dedicated institutional composition');
ok(html.includes('class="brand-full app-brand"'),'authenticated shell owns a compact composition');
ok(html.includes('class="brand-copy"'),'shell text is grouped without duplicating the brand');
equal((html.match(/<div class="title">MENTORIA BLACK<\/div><div class="sub">GESTÃO FINANCEIRA<\/div>/g)||[]).length,2,'login and shell each communicate the brand once');
ok(html.includes('alt="Símbolo oficial da Mentoria Black"'),'official symbol has meaningful alternative text');
ok(html.includes('<label for="loginEmail">E-mail</label>'),'email label is programmatically associated');
ok(html.includes('<label for="loginPassword">Senha</label>'),'password label is programmatically associated');
ok(html.includes('id="loginForm"'),'login contract is preserved');
ok(html.includes('id="signup"'),'account creation contract is preserved');
ok(html.includes('id="resetPass"'),'password recovery contract is preserved');
ok(html.includes('id="logout"'),'logout contract is preserved');
ok(html.includes('commercial/access-contract.js'),'commercial access runtime is preserved');
ok(html.includes('knowledge/knowledge-area.js'),'Knowledge runtime is preserved');
ok(css.includes('--gold: #C9A227'),'approved institutional gold is fixed');
ok(css.includes('--gold-hover: #E4C55B'),'approved hover gold is fixed');
ok(css.includes('--gold-dark: #8F741F'),'approved dark gold is fixed');
ok(css.includes('.brand-mark')&&css.includes('object-fit: contain'),'official mark remains proportional');
ok(css.includes('border: 0')&&css.includes('background: transparent'),'no artificial frame surrounds the symbol');
ok(css.includes(':focus-visible'),'keyboard focus stays visible');
ok(css.includes('min-height: 44px'),'interactive controls preserve accessible touch targets');
ok(css.includes('@media (max-width: 650px)'),'mobile shell has an explicit responsive treatment');
ok(css.includes('@media (prefers-reduced-motion: reduce)'),'reduced-motion preference is respected');
ok(!css.includes('display: none')||css.includes('.sub::before'),'CSS does not hide functional navigation');
ok(preview.includes('Preview local · sem Supabase'),'preview explicitly remains disconnected from Supabase');
ok(!/production-runtime|supabase|access-contract|knowledge-area\.js/.test(preview.replace('sem Supabase','')),'preview loads no production or backend runtime');
ok(preview.includes('?view=login')&&preview.includes('?view=app'),'preview exposes login and authenticated shell views');
ok(preview.includes('Conhecimento'),'preview keeps the homologated Knowledge navigation entry');
ok(!/fetch\(|createClient|signInWithPassword|rpc\(/.test(preview),'preview cannot perform remote operations');

console.log(`app-shell-branding: ${assertions} assertions passed`);
