const assert=require('assert');
const health=require('../js/health-integration');
let tests=0,assertions=0;
const equal=(actual,expected,message)=>{assertions++;assert.strictEqual(actual,expected,message)};
const ok=(value,message)=>{assertions++;assert.ok(value,message)};
const test=(name,fn)=>{try{fn();tests++}catch(error){error.message=`${name}: ${error.message}`;throw error}};
const NOW='2026-08-20';
const empty=()=>({plan:null,transactions:[],rules:[],goalsData:[],reserve:{balance:0,target:0,coverage:0,months:6},year:2026,month:8,now:NOW});
const run=overrides=>health.healthScore({...empty(),...overrides});
test('pesos-base permanecem 25/25/20/15/15 e somam 100%',()=>{equal(health.WEIGHTS.budget,.25);equal(health.WEIGHTS.investment,.25);equal(health.WEIGHTS.reserve,.20);equal(health.WEIGHTS.commitment,.15);equal(health.WEIGHTS.goals,.15);equal(Object.values(health.WEIGHTS).reduce((sum,value)=>sum+value,0),1)});
test('nenhum dado retorna estado explícito sem nota',()=>{const result=run();equal(result.score,null);equal(result.evaluable,false);equal(result.partial,false);equal(result.evaluatedComponents,0);equal(result.totalComponents,5);ok(result.message.includes('dados suficientes'));ok(result.components.every(item=>item.score===null&&!item.evaluable))});
test('somente orçamento renormaliza seu peso para 100%',()=>{const result=run({plan:{fixed_expenses:100}});equal(result.evaluable,true);equal(result.partial,true);equal(result.evaluatedComponents,1);equal(result.budgetScore,100);equal(result.commitmentScore,null);equal(result.score,100)});
test('orçamento e reserva renormalizam pesos 25/20',()=>{const result=run({plan:{fixed_expenses:100},reserve:{balance:50,target:100,coverage:.5,months:6}});equal(result.evaluatedComponents,2);equal(result.reserveScore,50);equal(result.score,78)});
test('todos os componentes usam pesos originais e avaliação completa',()=>{const result=run({plan:{revenue:1000,fixed_expenses:400,investments:100},transactions:[{id:'i',transaction_date:'2026-08-01',status:'realizado',transaction_type:'investimento',category:'Investimentos',amount:100,asset_id:'a'},{id:'f',transaction_date:'2026-08-02',status:'realizado',transaction_type:'despesa',category:'Gastos Fixos',amount:100}],goalsData:[{id:'g',name:'Carro',target:1000,current:500,deadline:'2027-01-01'}],reserve:{balance:600,target:600,coverage:6,months:6}});equal(result.evaluatedComponents,5);equal(result.partial,false);equal(result.reserveScore,100);equal(result.goalScore,50);equal(result.investScore,10);equal(result.score,70)});
test('score zero é válido quando existe base real avaliável',()=>{const result=run({plan:{revenue:1000}});equal(result.evaluable,true);equal(result.investScore,0);equal(result.score,0);equal(result.partial,true)});
test('programado e projetado não influenciam nota oficial',()=>{const plan={revenue:1000};const pending={id:'p',transaction_date:'2026-08-10',status:'pending',transaction_type:'investimento',category:'Investimentos',amount:500,asset_id:'a'};const rule={id:'r',next_date:'2026-08-15',active:true,frequency:'monthly',interval:1,transaction_type:'investimento',category:'Investimentos',amount:500,asset_id:'a'};const result=run({plan,transactions:[pending],rules:[rule]});equal(result.investScore,0);equal(result.score,0)});
test('entradas não são mutadas',()=>{const input=empty(),before=JSON.stringify(input);run(input);equal(JSON.stringify(input),before)});
test('comparação histórica registra fallback V81 versus não avaliado V82',()=>{const legacyEmpty=Math.round(75*.25+40*.25+0*.20+65*.15+70*.15),canonical=run();equal(legacyEmpty,49);equal(canonical.score,null);equal(canonical.evaluable,false)});
console.log(`health-canonical-v82: ${tests} tests, ${assertions} assertions passed`);
